// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAccountWidget: typeof import('./../src/modules/widgets/VAccountWidget.vue')['default']
    VAppBarDashboard: typeof import('./../src/layouts/widgets/VAppBarDashboard.vue')['default']
    VQLocaleTogglerWidget: typeof import('./../src/modules/widgets/VQLocaleTogglerWidget.vue')['default']
    VQThemeTogglerWidget: typeof import('./../src/modules/widgets/VQThemeTogglerWidget.vue')['default']
  }
}
