// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MoneyDashboard: typeof import('./../src/layouts/MoneyDashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAccountWidget: typeof import('./../src/layouts/blocks/widgets/VAccountWidget.vue')['default']
    VAppBarDashboard: typeof import('./../src/layouts/blocks/VAppBarDashboard.vue')['default']
    VBotMenuDashboard: typeof import('./../src/layouts/blocks/VBotMenuDashboard.vue')['default']
    VQLocaleTogglerWidget: typeof import('./../src/layouts/blocks/widgets/VQLocaleTogglerWidget.vue')['default']
    VQThemeTogglerWidget: typeof import('./../src/layouts/blocks/widgets/VQThemeTogglerWidget.vue')['default']
    VScoresWidget: typeof import('./../src/layouts/blocks/widgets/VScoresWidget.vue')['default']
  }
}
